apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: rollingUpdate
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: jithendar/user:image_tag
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/user"
            - name: REDIS_HOST
              value: redis-master
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
